# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'toone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
pod 'Charts/Realm'
pod 'Charts'
pod 'PNChart'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.8'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh'
pod "RATreeView", "~> 2.1.2"
  # Pods for toone

pod 'AMap3DMap'  #3D地图SDK
#pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使⽤用)
pod 'AMapSearch' #搜索功能
pod ‘AMapLocation’ #定位SDK

end
