# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'toone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
pod 'Charts/Realm'
pod 'Charts'
pod 'PNChart'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.8'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh'
  # Pods for toone
  
pod 'Pgyer'     #蒲公英
pod 'PgyUpdate'

end
